./" See http://www.fnal.gov/docs/products/ups/ReferenceManual/html/manpages.html for a good reference on manpages
.TH rmobj 1 1/23/2018 UMobj "rmobj Utility"

.SH NAME
rmobj - delete buckets and keys from an Object Store

.SH SYNOPSIS
rmobj [-h] [--version] [-D] [-V] [-A ACCESS_KEY] [-S SECRET_KEY]
             [-H HOST] [-P PORT] [-r] [-f] [-i]
             S3PATH [S3PATH ...]

.SH DESCRIPTION
rmobj deletes keys and buckets from an Object Store.

\fBBUCKET\fR is mandatory.  Specifying a \fBKEY\fR will allow keys with that prefix to be deleted.

rmobj will not delete directories unless the recursive option is specified.

.SH OPTIONS SUMMARY
Here is a short summary of the options available in rmobj.  Please refer to the \fBOPTIONS\fR section below for more detailed descriptions.

 -A, --access_key=<access_key>  Object store access key
 -S, --secret_key=<secret_key>  Object store secret key
 -H, --host=<host>              Object store server name
 -P, --port=<port>              Object store server port [Default: 443]
 -r, --recursive                Delete files and directories recursively
 -f, --force                    Ignore nonexistent keys, and never prompt
 -i, --interactive              Prompt before each deletion
     --version                  Print version
 -V, --verbose                  Verbose mode
 -D, --debug                    Debug mode
 -h, --help                     Help message

.SH OPTIONS

.TP
\fB-A, --access_key=<access_key>\fR
This option allows you to specify an Object Store access key.  If not supplied, rmobj will use the value of the environment variable \fIOBJ_ACCESS_KEY_ID\fR.

.TP
\fB-S, --secret_key=<secret_key>\fR
This option allows you to specify an Object Store secret key.  If not supplied, rmobj will use the value of the environment variable \fIOBJ_SECRET_ACCESS_KEY\fR.

.TP
\fB-H, --host=<host>\fR
This option allows you to specify an Object Store server.  If not supplied, rmobj will use the value of the environment variable \fIOBJ_SERVER\fR.

.TP
\fB-P, --port=<port>\fR
Object Store server port [Default: 443]

.TP
\fB-r/--recursive\fR
Remove directories and their contents recursively.  Mandatory for removing directories or the bucket.  Specifying recursive will prompt once for the whole delete operation.

.TP
\fB-f/--force\fR
Ignore any nonexistant keys, and never prompt the user.  Overrides the \fB--interactive\fR (\fB-i\fR) option.  The force flag will always cause the status code at program exit to be zero for key operation failures.

.TP
\fB-i/--interactive\fR
Prompt for confirmation before deleting each file.  This option will be ignored if \fB-f\fR is given.

.TP
\fB--version\fR
Print the version.

.TP
\fB-V/--verbose\fR
Allow for more verbose output.

.TP
\fB-D/--debug\fR
Running in debug mode prints detailed information about the calls being made against the Object Store.  This debugging information can be useful to UMIACS Staff if you have encountered a problem and need assistance.

.TP
\fB-h, --help\fR
Help menu

.SH AUTHOR
UMIACS Staff

.SH SEE ALSO
bagobj(1), catobj(1), chobj(1), cmpobj(1), cpobj(1), lsobj(1), mkobj(1),
mvobj(1), streamobj(1), syncobj(1), webobj(1)
