Document: umobj
Title: Debian umobj Manual
Author: <insert document author here>
Abstract: This manual describes what umobj is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/umobj/umobj.sgml.gz

Format: postscript
Files: /usr/share/doc/umobj/umobj.ps.gz

Format: text
Files: /usr/share/doc/umobj/umobj.text.gz

Format: HTML
Index: /usr/share/doc/umobj/html/index.html
Files: /usr/share/doc/umobj/html/*.html
